name: apiverve_historicalevents
description: Historical Events is a simple tool for getting historical events. It returns a list of historical events between 300BC and 2012
version: 1.1.14
homepage: https://apiverve.com/marketplace/historicalevents?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/historicalevents-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
